twitter/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from posts.views import view_404


urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('',include('posts.urls')),
    path('kullanici/',include('user.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),
    path("reset_password_sent/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset_password_complete", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('passwordResetDone/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),
]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler404 = 'posts.views.view_404'
handler500 = 'posts.views.view_500'

user/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('kayit/', register, name="register"),
    path('cikis/',userLogout, name ="logout"),
    path('profil/<str:slug>', profile, name = "profile"),
    path('yer-isaretleri/', savedTweets, name = "savedTweets"),
    path('duzenle/', change, name = "change"),
    path('back/', back, name = "back")
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.utils.text import slugify
from django.core.mail import send_mail
from django.conf import settings
# paste this at the start of code

# Create your models here.
class Post(models.Model):
  id = models.UUIDField(primary_key = True, unique = True, db_index = True, default = uuid.uuid4, editable= False)
  owner = models.ForeignKey('user.Profile', on_delete = models.CASCADE, verbose_name ="Yazar")
  content = models.TextField(verbose_name = "Tweet")
  image = models.ImageField(upload_to='posts/', verbose_name="Resim", blank=True, null = True)
  like = models.ManyToManyField('user.Profile',related_name="likes", verbose_name="Beğenenler", blank=True, symmetrical= False)
  saves = models.ManyToManyField('user.Profile',related_name="saves", verbose_name="Kaydedenler", blank=True)
  retweet = models.ManyToManyField('user.Profile',related_name="retweet", verbose_name="Retweet", blank=True)
  view = models.ManyToManyField('user.Profile', related_name="views", verbose_name="Görüntüleyenler", blank=True)
  created_at = models.DateTimeField(auto_now_add = True, verbose_name = "Oluşturulma Tarihi")
  slug = models.SlugField(blank= True, null= True)

  def __str__(self):
      return self.owner.name

  def save(self, *args, **kwargs):
    self.slug = slugify(self.content.replace('ı', 'i'))
    super().save(*args, **kwargs)
  
  class Meta:
     verbose_name_plural = "Tweetler"
     verbose_name = "Tweet"
     ordering = ["-created_at"]  
     
# Yorum yapan
# yorum yapılan post
# yorum yaptığı tarih
# yorum    
class Comment(models.Model):
  id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
  owner = models.ForeignKey('user.Profile', on_delete = models.CASCADE, verbose_name = "Yorum yapan")
  post = models.ForeignKey(Post, on_delete = models.CASCADE, verbose_name = "yorum yapılan Post")
  comment = models.TextField(max_length = 200, verbose_name = "Yorum")
  created_at = models.DateTimeField(auto_now_add = True, verbose_name = "Yorum yapılan Tarih")
  
  def __str__(self):
    return self.owner.name

  class Meta:
    verbose_name_plural = "Yorumlar"
    verbose_name = "Yorum"
    ordering = ['-created_at']
    

class Notificate(models.Model):
  ACTIONS = (
    ('begeni', 'Beğenme'),
    ('retweet', 'Retweet'),
    ('kaydetme', 'Kaydetme'),
    ('takip', 'Takip'),
    ('yorum', 'Yorum')
  )
  receiver = models.ForeignKey('user.Profile', on_delete = models.CASCADE, verbose_name = "Bildirim Alan")
  sender = models.ForeignKey('user.Profile', on_delete = models.CASCADE, verbose_name = "Bildirim Gönderen", related_name = "send")
  post = models.ForeignKey(Post, on_delete = models.CASCADE, verbose_name = "İşlem yapılan Post", null = True)
  action = models.CharField(max_length=50, choices = ACTIONS, verbose_name = "İşlem")
  message = models.TextField(blank=True, null = True, verbose_name = "İşlem Mesajı")
  isRead = models.BooleanField(default = False, verbose_name = "Okundu Bilgisi")
  created_at = models.DateTimeField(auto_now_add = True, null = True)
  def __str__(self):
    return self.receiver.name + " " + self.action
  
  class Meta:
    verbose_name_plural = "Bildirimler"
    verbose_name = "Bildirim"
    
  def save(self, *args, **kwargs):
    super().save(*args, **kwargs)
    count = Notificate.objects.filter(receiver = self.receiver, isRead = False).count()
    print(count)
    if count == 5 or count == 10:
      print("Çalıştı")
      subject = "Yeni Bildirimleriniz var"
      message = "Kullanıcılar sizin hesabınızla etkileşime girdiler. Bildirimlerinizi kontrol edin"
      send_mail(
        subject,
        message,
        settings.EMAIL_HOST_USER,
        [self.receiver.user.email],
        fail_silently=False
      )
    

user/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.utils.text import slugify
# Create your models here.

class Profile(models.Model):
  id = models.UUIDField(primary_key = True, unique = True, db_index = True, default = uuid.uuid4, editable = False)
  user = models.OneToOneField(User, on_delete = models.CASCADE)
  name = models.CharField(max_length = 200, verbose_name = "İsim Soyisim")
  bio =  models.TextField(("Hakkımda"), blank=True, null=True, default = "Merhaba, Ben twitter kullanıyorum.")
  follow = models.ManyToManyField('self', symmetrical=False, related_name="takip", verbose_name= "Takip edilenler", blank=True)
  follower = models.ManyToManyField('self', symmetrical=False, related_name="takipci", verbose_name= "Takipçiler", blank=True)
  image = models.ImageField(upload_to="profiles/", verbose_name="Profil Resmi")
  created_at = models.DateTimeField(auto_now_add = True)
  slug = models.SlugField(blank=True, null=True, editable = False)

  # symmetrical
  # mervan -> admin
  # admin <- mervan
  
  def save(self, *args, **kwargs):
    self.slug = slugify(self.user.username)
    super().save(*args, **kwargs)
  
  def __str__(self):      
    return self.user.username
  
  class Meta:
    verbose_name_plural = "Profiller"
    verbose_name = "Profil"
    ordering = ['-created_at']
  

user/forms.py
from django.forms import ModelForm
from .models import *
from django.contrib.auth.models import User

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'bio', 'image']
        
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'form-control'})
            

user/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.models import User
from .models import *
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from posts.models import *
from posts.views import userActions
from .forms import *
from django.core.cache import cache
# Create your views here.


def register(request):
  if request.method == "POST":
    if 'register' in request.POST:
      username = request.POST.get('username')
      name = request.POST.get('name')
      email = request.POST.get('email')
      password1 = request.POST.get('password1')
      password2 = request.POST.get('password2')
      gender = request.POST.get('gender')
      if password1 == password2:
        if User.objects.filter(username = username).exists():
          messages.error(request, 'Bu kullanıcı adı zaten mevcut!')
        elif User.objects.filter(email = email).exists():
          messages.error(request, 'Bu email daha önce kullanılmış!')
        elif len(password1) < 6:
          messages.error(request, 'Şifreniz en az 6 karakter olmalıdır!')
        elif username in password1 or name in password1 or email in password1:
          messages.error(request, 'Şifrenizin ile diğer bilgiler benzer olmamalıdır!')
        elif password1.isnumeric():
          messages.error(request,'Şifreniz sadece sayı içeremez!')
        else:
          user = User.objects.create_user(username = username , email = email, password=password1)
          user.save()
          profile = Profile.objects.create(
            user = user,
            name = name,
          )
          if gender == "female":
            profile.image = "profiles/defImgFemale.png"
          else:
            profile.image = "profiles/defImg.jpg"
          profile.save()
          login(request,user)
          messages.success(request, 'Kaydınız başarıyla oluşturuldu.')
          return redirect('index')
    if 'login' in request.POST:
      username = request.POST.get('username')
      password = request.POST.get('password') 

      user = authenticate(request, username = username, password = password)   

      if user is not None:
        cache_userkey = f"kullanıcı : {username}"
        hata = cache.get(cache_userkey, 0)
        print(hata)
        print(cache_userkey)
        if hata >= 3:
          messages.error(request, 'Hesabınız kilitli olduğu için giriş yapamazsınız')
          return redirect('register')
        login(request, user)
        cache.delete(cache_userkey)
        messages.success(request, 'Giriş Yaptınız.')
        next = request.GET.get('next')
        if next:
          return redirect(next)
        else:
          return redirect('index')
      else:
        cache_userkey = f"kullanıcı : {username}"
        hata = cache.get(cache_userkey, 0)
        hata += 1
        if hata >=3 :
          messages.error(request, 'Üst üste hatalı girdiniz. Hesabınız geçici süreliğine kilitlendi')
          return redirect('register')
        cache.set(cache_userkey, hata, 300)
        messages.error(request, "Kullanıcı adınız veya şifreniz hatalı")
  return render(request, 'user/loginPage.html')

def userLogout(request):
  logout(request)
  messages.success(request, 'Çıkış Yaptınız')
  return redirect('register')


def profile(request, slug):
  meta = request.META.get('HTTP_REFERER') # bir önceki sayfanın linkini çekiyoruz
  cache.set('meta', meta) # meta değişkenini önbelleğe atıyoruz
  profil = Profile.objects.get(slug = slug)
  likes = Post.objects.filter(like__in = [profil]) # postu beğenenler arasında profil olanları filtrele
  retweets = Post.objects.filter(retweet__in = [profil])
  if request.method == 'POST':
    myProfile = request.user.profile
    if 'follow' in request.POST:
      if myProfile in profil.follower.all():
        myProfile.follow.remove(profil)
        profil.follower.remove(myProfile)
      else:
        myProfile.follow.add(profil)
        profil.follower.add(myProfile)  
        yeniBildirim = Notificate(
          receiver = profil,
          sender = myProfile,
          action = 'takip'
        )
        yeniBildirim.message = f"{yeniBildirim.sender.name} kullanıcısı seni takip etmeye başladı"
        yeniBildirim.save()
      profil.save()
      myProfile.save()
      return redirect('profile', slug = profil.slug)
    else:
      userActions(request)
      return redirect('profile', slug = profil.slug)
  context = {
    'profil':profil,
    'likes':likes,
    'retweets':retweets
  }
  return render(request, 'user/profile.html', context)

def savedTweets(request):
  posts = Post.objects.filter(saves__in = [request.user.profile])
  if request.method == 'POST':
    userActions(request)
    return redirect('savedTweets')
  context = {
    'posts':posts
  }
  return render(request, 'explore.html', context)


def change(request):
  profilForm = ProfileForm(instance = request.user.profile)
  username = request.user.username
  email = request.user.email
  if request.method == 'POST':
    if 'update' in request.POST:
      profilForm = ProfileForm(request.POST, request.FILES, instance = request.user.profile)
      newUsername = request.POST.get('username')
      newEmail = request.POST.get('email') # boş olursa none gelir
      if profilForm.is_valid():
        profilForm.save()
        if newUsername and newEmail: # dolu mu 
          if newUsername != username: # yeni girilen kullanıcı adı ile eskisi aynı değilse (yani değiştirildiyse)
            if User.objects.filter(username = newUsername).exists():
              messages.error(request, 'Bu kullanıcı zaten mevcut')
              return redirect('change')
            else:
              request.user.username = newUsername
          if newEmail != email:
            request.user.email = newEmail 
          request.user.save()
          return redirect('profile', slug = request.user.profile.slug)
    if 'change' in request.POST:
      oldPassword = request.POST.get('oldPassword')
      newPassword1 = request.POST.get('newPassword1')
      newPassword2 = request.POST.get('newPassword2')
      
      user = authenticate(request, username = request.user, password = oldPassword)
      
      if user is not None:
        if newPassword1 == newPassword2:
          user.set_password(newPassword1)
          user.save()
          messages.success(request, 'Şifre değiştirildi')
          return redirect('register')
        else:
          messages.error(request, 'Şifreler uyuşmuyor')
      else:
        cache_userkey = f"kullanıcı : {request.user}"
        print(cache_userkey)
        hata = cache.get(cache_userkey, 0)
        hata += 1
        cache.set(cache_userkey, hata, 500)
        if hata == 3:
          logout(request)
          messages.error(request, 'Çok fazla deneme yaptığınız için hesabınız geçici süreliğine kilitlendi')
          return redirect('register')
        
        messages.error(request, 'Mevcut şifrenizi hatalı girdiniz')
      
  context = {
    'profilForm':profilForm,
    'username':username,
    'email':email
  }
  return render(request, 'user/settings.html', context)

# Geri dönme fonksiyonu
def back(request):
  meta = cache.get('meta')
  return redirect(meta)

templates/user/loginPage.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" type="image/x-icon">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link rel="stylesheet" href="/static/css/change.css">
  <title>X'e giriş yap /X</title>
</head>
<body style="background-color: #999;">
  
  <div class="container border-2 rounded-5 bg-warning-subtle w-50  ">
    {% if messages %}
              
      {% for mesaj in messages %}
        <div class="alert alert-{{mesaj.tags}} text-center">
          {{mesaj}}
        </div>
      {% endfor %}
        
    {% endif %}
    <div class="input ">
      <form method="POST" class="text-white my-3 ">
        {% csrf_token %}
        <input type="text" name="username" placeholder="kullanıcı adı" class="form-control border-1 rounded-3 ">
        <br>
        <input type="password" name="password" id="" placeholder="password" class="form-control border-1 rounded-3 ">
        <button class="btn btn-danger my-2 " type="submit" name="login">Giriş Yap</button>
      </form>
      <a href="{% url 'reset_password' %}">Şifremi Unuttum</a>
    </div>
  
  </div>


<div class="wrapperPageLogin">
  <div class="loginBoxWrapper">

<div class="loginBox">
<div class="upleft">
  <i class="fa-solid fa-xmark markx"></i>
  <div class="loginCenter">
    <i class="fa-brands fa-x-twitter logintwitter"></i>
  </div>
</div>

<div class="d-flex">
  
  <div class="register centerTwitterLogin">
    <form method="POST">
      {% csrf_token %}

      <div class="form ms-5 ">
        <label for="" class="fs-5 ">Kullanıcı adı</label>
        <input type="text" name="username" required placeholder="Kullanıcı adını giriniz" id="" class="form-control border-1 rounded-3">
        <label for="" class="fs-5">İsim Soyisim</label>
        <input type="text" name="name" id="" required  placeholder="İsim Soyisim"class="form-control border-1  rounded-3 ">
        <label for="" class="fs-5">Email</label>
        <input type="text" name="email" id="" class="form-control border-1  rounded-3 " placeholder="Email" required> 
        <label for="" class="fs-5">Şifrenizi Giriniz</label>
        <input type="password" name="password1" id="" class="form-control border-1  rounded-3 " placeholder="Şifre" required>
        <label for="" class="fs-5">Şifrenizi Onaylayın</label>
        <input type="password" name="password2" id="" class="form-control border-1  rounded-3 " placeholder="Şifre" required>
        <select name="gender" id="" class="w-100 fs-6 ">
          <option value="male" class="fs-6" selected>Erkek</option>
          <option value="female" class="fs-6">Kadın</option>
        </select>
        <input type="submit" value="Kayıt Ol" name="register" class="btn btn-danger ">
        <div class="form">

      </div>


</div>




<script src="./script.js"></script>
<script src="https://kit.fontawesome.com/4248051235.js" crossorigin="anonymous"> </script>
</body>

</html>

templates/user/profile.html
{% extends 'index.html' %}
{% load humanize %}


{% block title %}
  <title>Profil / X</title>
{% endblock title %}
  
  

{% block main %}
  

  
        <div class="row w-100 ">
          <div class="d-flex mt-1 mb-2">
            <div class="m-2 p-2 ps-3 pe-3 rounded-5 onHover">
              <a href="{% url 'back' %}"><i class="fa-solid fa-arrow-left" style="color: #ffffff;"></i></a>
            </div>
            <div>
              <a href="{% url 'profile' profil.slug %}" class="fs-4 d-block text-decoration-none text-light">
                <strong>
                  {{profil.name}}
                </strong>
              </a>
              <a href="{% url 'profile' profil.slug %}" class="fs-6 text-secondary d-block text-decoration-none ">{{profil.post_set.all.count}} gönderi</a>
            </div>
          </div>
        </div>

        <div class="row w-100 wallPaper overflow-hidden ">
          <img src="/static/img/wallpaper.jpeg" alt="">
        </div>

        <div class="d-flex align-items-center justify-content-between">
          <img src="{{profil.image.url}}" alt="" width="140" height="140" class="rounded-circle profilPic">
          
          {% if request.user.profile == profil %}
          <a href="{% url 'change' %}" class="btn btn-dark bg-black border-secondary border-1  me-4 rounded-5">Profili düzenle</a>
          {% else %}  
            <form method="POST">
              {% csrf_token %}
              <button type="submit" name="follow" class="btn btn-dark bg-black border-secondary border-1  me-4 rounded-5">
                
                {% if request.user.profile in profil.follower.all %} <!-- Profiline girdiğimiz kullanıcın takipçileri arasında bizim hesabımız varsa  -->
                  Takipten Çık
                {% else %}
                  Takip et
                {% endif %}
                  
              </button>
            </form>
          {% endif %}
            
        </div>


        <!-- Profil Begin -->
        <div class="w-100">
          <div class="pt-2 ">
            <div class="mb-4 ">
              <a href="#" class="text-white text-decoration-none d-block  fs-5">{{profil.name}}</a>
              <a class="fs-6 link-secondary text-decoration-none d-block " href="#">@{{profil.user.username}}</a>

              <span>{{profil.bio}}</span>
             
              <span class="text-secondary d-block fs-6 mb-2 "> <i class="fa-solid fa-calendar-days "></i> 
                {{profil.created_at|naturalday}}
                
                {% if profil.created_at|naturalday == "bugün" or profil.created_at|naturalday == "dün" %}
                 
                {% else %}
                tarihinde
                {% endif %}
                  
                katıldı
              </span>
              <div>
                <a href="#" class="text-secondary text-decoration-none fs-6 me-4"> <span class="text-light">{{profil.follow.all.count}}</span> Takip edilen </a>
                <a href="#" class="text-secondary text-decoration-none fs-6"><span class="text-light">{{profil.follower.all.count}}</span> Takipçi</a>
              </div>
            </div>

            <div class="row w-100 border-bottom">
              <div class="col-3 zamanAkisi postes d-flex align-items-center justify-content-center pt-2 ">
                <div class="tablinks active" onclick="openTab(event, 'gonderi')">
                  <p class=""><strong>Gönderiler</strong></p>
                </div>
              </div>
              <div class="col-3 zamanAkisi postes d-flex align-items-center justify-content-center pt-2 ">
                <div class="tablinks" onclick="openTab(event, 'yanit')">
                  <p class=""><strong>Yanıtlar</strong></p>
                  
                </div>
              </div>
              <div class="col-3 zamanAkisi postes d-flex align-items-center justify-content-center pt-2 ">
                <div class="tablinks" onclick="openTab(event, 'retweet')">
                  <p class=""><strong>Retweetler</strong></p>
                  
                </div>
              </div>
              <div class="col-3 zamanAkisi postes d-flex align-items-center justify-content-center pt-2 ">
                <div class="tablinks" onclick="openTab(event, 'begeni')">
                  <p class=""><strong>Beğeni</strong></p>
                </div>
              </div>
            </div>
          </div>
          <!-- Profil Fin -->

          <!-- Tweetler -->
          <div class="tabcontent show" id="gonderi">
            
            {% for post in profil.post_set.all %}
              {% include 'partials/_tweet.html' %}
            {% endfor %}
              
          </div>
           <!-- ### Tweetler ### -->

          <!-- Yanıtlar -->
          <div class="tabcontent" id="yanit">
            
            {% for post in profil.comment_set.all %}
                <div class="row border-top my-2">
                  <div class="col-2 pt-2 ">
                      <img src="{{post.owner.image.url}}" alt="" width="50" height="50" class="rounded-circle me-2">
                  </div>
                  <div class="col-10 pt-2 ">
                      <div>
                        <a href="#" class="text-white text-decoration-none fs-5">{{post.owner.name}}</a>
                        <a class="fs-6 link-secondary text-decoration-none" href="#">@{{post.owner.user.username}}</a>
                        <a class="fs-6 link-secondary text-decoration-none" href="">・{{post.created_at|naturaltime}}</a>
                      </div>
                      <div>
                        <p>@{{post.post.owner.user}} {{post.comment}}</p>
                      </div> 
                  </div>
                </div>
            {% endfor %}
              
          </div>
           <!-- ### Yanıtlar ### -->

           <!-- Beğeniler -->
           <div class="tabcontent" id="begeni">
            
            {% for post in likes %}
              {% include 'partials/_tweet.html' %}
            {% endfor %}
              
           </div>
           <!-- ### Beğeniler ### -->


           <!-- Retweetler -->
           <div class="tabcontent" id="retweet">
            
            {% for post in retweets %}
              {% include 'partials/_tweet.html' %}
            {% endfor %}
              
           </div>
           <!-- ### Retweetler ### -->
        </div>
        {% endblock main %}

templates/user/settings.html
{% extends 'index.html' %}


{% block main %}
    <form method="POST" class="mt-3" enctype="multipart/form-data">
        {%  csrf_token %}
        <label for="">Kullanıcı Adı</label>
        <input type="text" name="username" value="{{username}}" class="form-control" id="">
        <label for="">Email</label>
        <input type="email" name="email" value="{{email}}" id="" class="form-control">

        {{profilForm}}
       
        <input type="submit" value="Güncelle" name="update" class="btn btn-primary">


        <hr class="my-4">

        <h3>Şifre Değiştir</h3>

        <label for="">Mevcut Şifre</label>
        <input type="password" name="oldPassword" id="" class="form-control">
        <label for="">Yeni Şifre</label>
        <input type="password" name="newPassword1" id="" class="form-control">
        <label for="">Şifreyi onaylayın</label>
        <input type="password" name="newPassword2" id="" class="form-control">


        <input type="submit" value="Değiştir" name="change" class="btn btn-primary mt-2">
    </form>
{% endblock main %}
    